name: CI Pipeline

on:
  push:
    branches: [ main, ci-pipeline ]
  pull_request:
    branches: [ main, ci-pipeline ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package --batch-mode

      - name: Run Tests
        run: mvn test --batch-mode